//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3649
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3649 版自动生成。
// 
#pragma warning disable 1591

namespace vpms.vms {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RecordServcieSoap11", Namespace="http://www.sdhuijin.cn/record/definition")]
    public partial class RecordServcieService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetControllerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RecordServcieService() {
            this.Url = global::vpms.Properties.Settings.Default.vpms_vms_RecordServcieService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetControllerListCompletedEventHandler GetControllerListCompleted;
        
        /// <remarks/>
        public event RecordCompletedEventHandler RecordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetControllerListResponse", Namespace="http://www.sdhuijin.cn/record/schema/v1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Controller", IsNullable=false)]
        public Controller[] GetControllerList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.sdhuijin.cn/record/schema/v1")] GetControllerListRequest GetControllerListRequest) {
            object[] results = this.Invoke("GetControllerList", new object[] {
                        GetControllerListRequest});
            return ((Controller[])(results[0]));
        }
        
        /// <remarks/>
        public void GetControllerListAsync(GetControllerListRequest GetControllerListRequest) {
            this.GetControllerListAsync(GetControllerListRequest, null);
        }
        
        /// <remarks/>
        public void GetControllerListAsync(GetControllerListRequest GetControllerListRequest, object userState) {
            if ((this.GetControllerListOperationCompleted == null)) {
                this.GetControllerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetControllerListOperationCompleted);
            }
            this.InvokeAsync("GetControllerList", new object[] {
                        GetControllerListRequest}, this.GetControllerListOperationCompleted, userState);
        }
        
        private void OnGetControllerListOperationCompleted(object arg) {
            if ((this.GetControllerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetControllerListCompleted(this, new GetControllerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RecordResponse", Namespace="http://www.sdhuijin.cn/record/schema/v1")]
        public RecordResponse Record([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.sdhuijin.cn/record/schema/v1")] RecordRequest RecordRequest) {
            object[] results = this.Invoke("Record", new object[] {
                        RecordRequest});
            return ((RecordResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RecordAsync(RecordRequest RecordRequest) {
            this.RecordAsync(RecordRequest, null);
        }
        
        /// <remarks/>
        public void RecordAsync(RecordRequest RecordRequest, object userState) {
            if ((this.RecordOperationCompleted == null)) {
                this.RecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecordOperationCompleted);
            }
            this.InvokeAsync("Record", new object[] {
                        RecordRequest}, this.RecordOperationCompleted, userState);
        }
        
        private void OnRecordOperationCompleted(object arg) {
            if ((this.RecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecordCompleted(this, new RecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sdhuijin.cn/record/schema/v1")]
    public partial class GetControllerListRequest {
        
        private string anyStringField;
        
        /// <remarks/>
        public string anyString {
            get {
                return this.anyStringField;
            }
            set {
                this.anyStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sdhuijin.cn/record/schema/v1")]
    public partial class Controller {
        
        private string idField;
        
        private string snField;
        
        private string ipField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string sn {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sdhuijin.cn/record/schema/v1")]
    public partial class RecordRequest {
        
        private string controllerSnField;
        
        private string readerNumberField;
        
        private string cardNumberField;
        
        /// <remarks/>
        public string controllerSn {
            get {
                return this.controllerSnField;
            }
            set {
                this.controllerSnField = value;
            }
        }
        
        /// <remarks/>
        public string readerNumber {
            get {
                return this.readerNumberField;
            }
            set {
                this.readerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sdhuijin.cn/record/schema/v1")]
    public partial class RecordResponse {
        
        private string commandField;
        
        private string gateNumberField;
        
        /// <remarks/>
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        public string gateNumber {
            get {
                return this.gateNumberField;
            }
            set {
                this.gateNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetControllerListCompletedEventHandler(object sender, GetControllerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetControllerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetControllerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Controller[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Controller[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RecordCompletedEventHandler(object sender, RecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RecordResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RecordResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591